/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HorizontalScroll: typeof import('./resources/js/components/tacotaf/HorizontalScroll.vue')['default']
    NotFound: typeof import('./resources/js/components/NotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sprite: typeof import('./resources/js/components/Sprite.vue')['default']
  }
}
